### ISSUE TITLE
setSource from useWallet hook seems to not function properly

### ISSUE THREAD

**Issue by Emilvooo** [vechain/vechain-dapp-kit#198]
👋 I'm encountering an issue where the setSource function from the useWallet hook does not seem to function correctly. Here's what I'm experiencing:

1. Within a custom hook, I invoke the setSource function from the useWallet hook. This hook also handles some other unrelated global state management tasks (see the provided code snippet for reference).
2. The console output indicates that the wallet source has been set successfully: [WalletManager] (setSource) wallet-connect.
3. In another custom hook, I utilize the useConnex hook to prepare for signing a transaction. This part works as expected. However, if I cancel the transaction or close the wallet connect modal, the source appears to be reset to null.
To address the issue where the source is reset to null after a user cancels a transaction or closes the wallet connect modal, I attempted to call setSource again before initiating the transaction signing process. Unfortunately, this does not seem to resolve the problem, as I encounter the "No wallet has been selected" error message. But in some scenarions the setSource before signing a transaction seems to work and set the source properly - but i can't really figure out why.

For additional context, I am not using the wallet connect functionality from the kit because I am leveraging VeChain.energy OAuth for user authentication. The kit is solely used for transaction signing, allowing users the flexibility to choose any wallet they prefer.

Custom hook for setting the source when check user related stuff:

    const { 
        loading,
        userWallet,
        setLoading,
        setUserWallet,
        setUserWalletSource,
    } = userStore();

    const { setSource } = useWallet();

    useEffect(() => {
        async function initialize() {
            try {
                const response = await fetch('/api/user');
                const data = await response.json();
                if (data.wallet !== null) {
                    setSource(data.source);
                    setUserWalletSource(data.source);
                    setUserWallet(data.wallet);
                }
            } catch (error) {
                console.error('Failed to initialize user data:', error);
            } finally {
                setLoading(false);
            }
        }

        initialize();
    }, []);

Custom hook for singing transactions:

    const { setSource } = useWallet();

    const signTransaction = async (clauses) => {
        setSource(userWalletSource); // here i'm setting the source to the userWalletSource which is from my global state in case the source has been reset to null; but this seems to not work properly
        
        try {
            const res = await vendor.sign("tx", [clauses]).delegate(DELEGATE_URL).request();
            
            await thor.ticker().next();
            const receipt = await thor.transaction(res.txid).getReceipt();
            if (!receipt || receipt.reverted) {
                toast.error("Transaction failed");
                return false;
            }
            
            toast.success("Transaction successful");
        } catch (error) {
            toast.error(error.message);
        } finally {
            close();
        }
    };

**Comment by davidecarpini** [comment]
Hey @Emilvooo,
the setSource function is used to set the wallet that you want to use to connect.
then you should use the connected Connex instance.

I created a branch for you with an example using the setSource with a custom setting

https://github.com/vechain/vechain-dapp-kit/compare/198-setsource-from-usewallet-hook-seems-to-not-function-properly?expand=1

https://github.com/vechain/vechain-dapp-kit/assets/5785838/e5c12501-3d04-4cd9-bb0f-968cc480f751

let me know if it helps you with your problem

**Comment by davidecarpini** [comment]
closing the issue for inactivity
