### ISSUE TITLE
Max gas argument doesn't get picked fropm VeWorld Wallet

### ISSUE THREAD

**Issue by GianBarGian** [vechain/vechain-dapp-kit#206]
I'm using the vendor instance to pass a max gas argument before signing a transaction: 
```ts
  const tx = await vendor
                .sign("tx", clauses)
                .gas(3000000)
                .comment(comment)
                .request();
```
 While it works fine using sync 2, it seems the argument to the gas method doesn't get passed to the veworld (web) wallet.

**Comment by fabiofvc** [comment]
Thank you @GianBarGian for your feedback.
May I ask you which Web Wallet were you using? 
Also the browser and the app version.
Ty 👍

**Comment by davidecarpini** [comment]
Thank you @GianBarGian I'll check it and let you know

**Comment by davidecarpini** [comment]
Hey @GianBarGian it's not a bug related to dapp-kit, it's a bug of the extension, I've just created a fix for that in the extension repo, it will be available in the next release.

I'll close the bug here since it's not related to dapp-kit
