### ISSUE TITLE
Dapp kit doesn't react on connection status changes on Next 14.2.X

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-dapp-kit#237]
Using Next version 14.2.1:

https://github.com/vechain/vechain-dapp-kit/assets/17639359/a9c9f000-8aef-48c5-b79b-5a11faf290f5

**Comment by Smuzzies** [comment]
Confirmed bug with 14.2.1

**Comment by Valazan** [comment]
This issue also applies to Next 15. @davidecarpini

**Comment by victhorbi** [comment]
@Valazan can you confirm/check if this ticket can be closed?

**Comment by davidecarpini** [comment]
this should have been fixed in the 1.0.15
