### ISSUE TITLE
Getting DAppKitUI not configured Error

### ISSUE THREAD

**Issue by AthiraVGopi** [vechain/vechain-dapp-kit#253]
Cloned angular sample project directly and used, while clicking connect wallet , getting the errors -
1) main.ts:4  ERROR TypeError: http_1.Agent is not a constructor
    at new SimpleNet (simple-net.js:24:24)
    at he (index.js:1:12541)
    at new Q (index.js:1:12697)
    at Object.configure (index.js:23:97112)
    at AppComponent.ngOnInit (app.component.ts:33:19)
    at callHookInternal (core.mjs:4024:14)
    at callHook (core.mjs:4051:13)
    at callHooks (core.mjs:4006:17)
    at executeInitAndCheckHooks (core.mjs:3956:9)
    at refreshView (core.mjs:13513:21)
handleError @ core.mjs:10614
(anonymous) @ core.mjs:28881
invoke @ zone.js:368
run @ zone.js:129
runOutsideAngular @ core.mjs:10979
(anonymous) @ core.mjs:28881
tick @ core.mjs:28745
_loadComponent @ core.mjs:28773
bootstrap @ core.mjs:28710
(anonymous) @ core.mjs:28227
invoke @ zone.js:368
onInvoke @ core.mjs:11083
invoke @ zone.js:367
run @ zone.js:129
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
(anonymous) @ core.mjs:10757
onInvokeTask @ core.mjs:10757
invokeTask @ zone.js:401
onInvokeTask @ core.mjs:11070
invokeTask @ zone.js:401
runTask @ zone.js:173
drainMicroTaskQueue @ zone.js:581
Zone - Promise.then (async)
onScheduleTask @ core.mjs:10751
scheduleTask @ zone.js:382
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
then @ zone.js:1442
(anonymous) @ core.mjs:28222
_callAndReportToErrorHandler @ core.mjs:28488
(anonymous) @ core.mjs:28219
invoke @ zone.js:368
onInvoke @ core.mjs:11083
invoke @ zone.js:367
run @ zone.js:129
run @ core.mjs:10934
internalCreateApplication @ core.mjs:28196
bootstrapApplication @ platform-browser.mjs:1020
14913 @ main.ts:4
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ ignored|D:\Project\QlikTag\sample-angular-app\node_modules\thor-devkit\node_modules\bn.js\lib|buffer:1
(anonymous) @ ignored|D:\Project\QlikTag\sample-angular-app\node_modules\thor-devkit\node_modules\bn.js\lib|buffer:1
__webpack_require__.O @ chunk loaded:23
(anonymous) @ ignored|D:\Project\QlikTag\sample-angular-app\node_modules\thor-devkit\node_modules\bn.js\lib|buffer:1
webpackJsonpCallback @ jsonp chunk loading:71
(anonymous) @ main.js:1

2)
core.mjs:10614 
 ERROR 
Error: DAppKitUI not configured
    at Object.get (index.js:23:97589)
    at get wallet (index.js:23:97350)
    at Q.handleOpen (index.js:247:132)
    at EventPart.handleEvent (lit-html.js:1327:35)
    at task.callback (zone.js:1622:49)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)

**Comment by darrenvechain** [comment]
@AthiraVGopi have you configured polyfills in your application? You can see an example here:

https://github.com/vechain/vechain-dapp-kit/blob/main/examples/sample-angular-app/angular.json#L26

**Comment by AthiraVGopi** [comment]
Hi @darrenvechain, polyfills are there, I am trying to run the sample-angular-app without any modifications. so example application throws same error whilr running

**Comment by darrenvechain** [comment]
Angular seems to work fine for me, and we also run it as part of the e2e tests in the CI. What is your node version?


https://github.com/vechain/vechain-dapp-kit/assets/107671032/143755ec-2079-4bcb-ad70-58da192993ff

**Comment by darrenvechain** [comment]
We also have https://vechain.github.io/vechain-dapp-kit/angular/

**Comment by AthiraVGopi** [comment]
@darrenvechain 

Angular CLI: 16.2.14       
Node: 16.14.2
Package Manager: npm 10.5.2
OS: win32 x64

these are the versions used

**Comment by AthiraVGopi** [comment]
cloned project worked successfully now, Thankyou @darrenvechain

**Comment by darrenvechain** [comment]
Is it possible to use v18?

We have this in the readme:

```md
### Prerequisites

-   Node.js >= 18.17
-   Yarn >= 1.22.10
```

**Comment by AthiraVGopi** [comment]
Angular CLI: 16.2.14       
Node: 18.20.0
Package Manager: npm 10.5.0
OS: win32 x64

Tried with this version getting same errors .

**Comment by darrenvechain** [comment]
Not sure whats going on there @AthiraVGopi , I've got different results on my side:


<img width="765" alt="image" src="https://github.com/vechain/vechain-dapp-kit/assets/107671032/5062dc4d-a9bb-4377-8642-7358feb71b03">
<img width="1399" alt="image" src="https://github.com/vechain/vechain-dapp-kit/assets/107671032/5a281552-4072-4cd4-9b96-3453f223b9aa">

**Comment by AthiraVGopi** [comment]
when importing dappkitui getting below error can you please check why this error coming?

my package.json is

{
  "name": "sample",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@caliatys/array-typer": "^1.0.0",
    "@ng-bootstrap/ng-bootstrap": "^15.0.1",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "@popperjs/core": "^2.11.8",
    "@vechain/dapp-kit": "^1.0.12",
    "@vechain/dapp-kit-ui": "^1.0.12",
    "angular-svg-icon": "^16.0.0",
    "assert": "2.1.0",
    "axios": "^1.4.0",
    "bootstrap": "^5.3.0",
    "buffer": "5.7.1",
    "crypto-browserify": "3.12.0",
    "https-browserify": "1.0.0",
    "os-browserify": "0.3.0",
    "rxjs": "~7.8.0",
    "stream-browserify": "3.0.0",
    "stream-http": "3.2.0",
    "tslib": "^2.3.0",
    "url": "^0.11.3",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.14",
    "@angular/cli": "^16.2.14",
    "@angular/compiler-cli": "^16.2.0",
    "@types/jasmine": "~4.3.0",
    "@vechain/repo-config": "https://github.com/vechain/repo-config#v0.0.1",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~4.9.5"
  }
}



Error: node_modules/@vechain/dapp-kit/dist/index.d.ts:230:45 - error TS2503: Cannot find namespace 'Connex'.

230 declare const DEFAULT_CONNECT_CERT_MESSAGE: Connex.Vendor.CertMessage;
                                                ~~~~~~


Error: node_modules/@vechain/dapp-kit/dist/index.d.ts:233:50 - error TS2503: Cannot find namespace 'Connex'.

233 declare const genesisBlocks: Record<NetworkType, Connex.Thor.Block>;
                                                     ~~~~~~


Error: node_modules/@vechain/dapp-kit/dist/index.d.ts:252:47 - error TS2503: Cannot find namespace 'Connex'.

252 declare const convertVendorToSigner: (vendor: Connex.Vendor) => Connex.Signer;
                                                  ~~~~~~


Error: node_modules/@vechain/dapp-kit/dist/index.d.ts:252:65 - error TS2503: Cannot find namespace 'Connex'.

252 declare const convertVendorToSigner: (vendor: Connex.Vendor) => Connex.Signer;
                                                                    ~~~~~~


Error: node_modules/@vechain/dapp-kit/dist/index.d.ts:264:61 - error TS2503: Cannot find namespace 'Connex'.

264 declare const normalizeGenesisBlock: (genesis?: Genesis) => Connex.Thor.Block;

**Comment by AthiraVGopi** [comment]
Hi @darrenvechain 

Implemented dappkit, i am using <vdk> button, can you tell me how can i manage some function according to connected and disconnected? 
how i can trigger a function when its connected?

**Comment by AthiraVGopi** [comment]
Hi @darrenvechain 
when i click on connect wallet, showing other than veworld, wallect connect and sync is showing, what i need to do for removing those options, for me only want veworld wallet option.

**Comment by AthiraVGopi** [comment]
Hi @darrenvechain ,

I am able to run and connect the vewallet from sample app using localhost. When I tried with a domain and selecting vewallet it is redirecting to "https://www.veworld.com/discover/browser/ul/http%3A%2F%2Fdev.l.qlt.io%2F%3For%3DVTJGc2RHVmtYMS83TmNVWlRRdTFZb1puZEdIajk0eGl4em5QRktLV1pFT1Z2eXpnaWJ6VlpPYUpvamVNbzhwMg"

not able to find the issue using domain in the project. the wallet list popup is coming but when selecting it will not working.
please explain the configuration need to add for routing to this app using domain.
