### ISSUE TITLE
🐛 Test & Solo-Networks fail with VeWorld since 1.0.12

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-dapp-kit#285]
I have upgraded dApp-kit to 1.0.13 and it fails to build transactions for TestNet and Solo using VeWorld.

My integration is as simple as:

```tsx
        <DAppKitProvider
            nodeUrl={NODE_URL}
            genesis={genesis}
            usePersistence
        >
            <DAppKitConsumers>{children}</DAppKitConsumers>
        </DAppKitProvider>
    );
```

- NODE_URL is either `https://node-testnet.vechain.energy` or `http://localhost:8669`
-geneiss is either `test` or the genesis block from the solo node

my transaction is done within react:

```tsx
import { useWallet, useConnex } from '@vechain/dapp-kit-react';

// ..

  const handleSend = async () => {
        try {
            const clauses = [
                {
                    ...clauseBuilder.functionInteraction(Addresses.X2EarnApp, abiFunc, []),
                }
            ]
            // build a transaction for the given clauses
            const tx = connex.vendor.sign('tx', clauses)
                .signer(account)

            // ask the user to sign the transaction
            const { txid } = await tx.request()

            // the resulting transaction id is stored to check for its status later
            setTxId(txid)
        }
        catch (err) {
            setError(String(err))
        }
}
```

The transaction is prompted for signing in VeWorld and is always built with chainTag `74`.

Downgrading to 1.0.11 solves the problem and it works. The issue seems to have started with 1.0.12.

Has the handling changed or is this an issue within the dapp kit?

**Comment by ifavo** [comment]
I must correct myself, I was able to reproduce and solve the issue by upgrading/downgrading dapp kit in a demo project and somehow it defaults back to 74 also on 1.0.11 again. Sorry for the confusion.

**Comment by ifavo** [comment]
I have can reproduce the problem now within VeWorld:

```shell
git clone https://github.com/vechain-energy/example-buy-me-a-coffee
npm install
npm start
```

Within the App:

1. connect
2. send a transaction: _this works_ (sends a transaction on testnet)
3. reload
4. send a transaction: _this fails_ (transation is built with chainTag from main net)

The problem seems to happen due the persistence feature in VeWorld, which does seem to lose the network used during connection.

Because I don't have a repository to place this issue for VeWorld, I will re-open it here. Is there a public repo for VeWorld?

**Comment by darrenvechain** [comment]
@ifavo I think this may be an issue in veworld, which is being looked at

**Comment by davidecarpini** [comment]
we are aware of this bug, guys are working on this on the veworld side, thanks for reporting tho 🙌 
I'm going to close this here

**Comment by ifavo** [comment]
@davidecarpini thanks a lot 🙏
